version: 2

defaults: &defaults
  working_directory: ~/qlik-network-chart
  docker:
    - image: circleci/node:stretch
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "network-vis-chart"
    PACKAGE_NAME: "qlik-network-chart"

jobs:
  build:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn eslint
      - run:
          name: BlackDuck scan
          command: curl -s https://detect.synopsys.com/detect.sh | bash -s -- \
            --blackduck.url="https://qliktech.blackducksoftware.com" \
            --blackduck.trust.cert=true \
            --blackduck.username="svc-blackduck" \
            --blackduck.password=${svc_blackduck} \
            --detect.project.name="viz-bundle-qlik-network-chart"
      - run:
          name: Build
          command: yarn build && yarn sense
          environment:
            NODE_ENV: production
      - run:
          name: Update spec
          command: yarn run spec
      - run:
          name: Run unit tests
          command: yarn test:unit
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  master_flow:
    jobs:
      - build
